<?php
$language = "en-US";
$title = "Maria's Room";
$HEADER1 = "SIGN UP NOW AND GET ";
$HEADER2 = "150% WELCOME BONUS";
$SUBHEADER = "DEPOSIT A MINIMUM OF $300 AND YOU WILL RECEIVE A PRIVATE AND PERSONALIZED VIDEO FROM MARIA OZAWA!";
$BANNERLINK1 = "Play Video";
$BANNERLINK2 = "Join Now";
?>